development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: dave  
  password: fay586tb
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: dave
  password: fay586tb